#!/bin/bash

VERBOSE=""

while [ $# -gt 1 ]
do
  if [ "$1" == "--" ]; then
    shift
    exec $*
    exit $?
  fi

  if [ "$1" == "" ]; then
    echo "no more..."
    exit 1
  fi

  if [ "$1" == "-v" ]; then
    VERBOSE=1
  else
    if [ -f "$1" ]; then
      if [ $VERBOSE ]; then
        echo "parse '$1'..." >&2
      fi
      export $(grep -v '^#' $1 | xargs -d '\n')
    else
      echo "'$1' not found - ignored" >&2
    fi
  fi
  shift
done